app:
    resource: "@AppBundle/Controller/"
    type:     annotation

place:
    resource: "@PlaceBundle/Resources/config/routing.yml"
    prefix:   /place

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /


# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

