<?php

namespace PlaceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CheckpointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckpointRepository extends EntityRepository
{
}
