homepage:
    path:     /
    defaults: { _controller: UserBundle:Home:show }

user_map:
    path:     /user/map
    defaults: { _controller: UserBundle:Map:show }

place_informations:
    path:     /user/place/{id}
    defaults: { _controller: UserBundle:Place:show }